Resources:
  aws-ec2-eip: aws_eip
  aws-ec2-vpc: aws_vpc
  aws-ec2-host: aws_ec2_host
  aws-ec2-route: aws_route
  aws-ec2-subnet: aws_subnet
  aws-ec2-volume: aws_ebs_volume
  aws-ec2-flowlog: aws_flow_log
  aws-ec2-keypair: aws_key_pair
  aws-ec2-ec2fleet: aws_ec2_fleet
  aws-ec2-instance: aws_instance
  aws-ec2-ipampool: aws_vpc_ipam_pool
  aws-ec2-ipam: aws_vpc_ipam
  aws-ec2-ipamscope: aws_vpc_ipam_scope
  aws-ec2-spotfleet: aws_spot_fleet_request
  aws-ec2-natgateway: aws_nat_gateway
  aws-ec2-networkacl: aws_network_acl
  aws-ec2-prefixlist: aws_ec2_managed_prefix_list
  aws-ec2-routetable: aws_route_table
  aws-ec2-vpngateway: aws_vpn_gateway
  aws-ec2-dhcpoptions: aws_vpc_dhcp_options
  aws-ec2-routeserver: aws_vpc_route_server
  aws-ec2-vpcendpoint: aws_vpc_endpoint
  aws-ec2-ipampoolcidr: aws_vpc_ipam_pool_cidr
  aws-ec2-vpccidrblock: aws_vpc_ipv4_cidr_block_association
  aws-ec2-securitygroup: aws_security_group
  aws-ec2-vpnconnection: aws_vpn_connection
  aws-ec2-carriergateway: aws_ec2_carrier_gateway
  aws-ec2-clientvpnroute: aws_ec2_client_vpn_route
  aws-ec2-eipassociation: aws_eip_association
  aws-ec2-ipamallocation: aws_vpc_ipam_pool_cidr_allocation
  aws-ec2-launchtemplate: aws_launch_template
  aws-ec2-placementgroup: aws_placement_group
  aws-ec2-transitgateway: aws_ec2_transit_gateway
  aws-ec2-customergateway: aws_customer_gateway
  aws-ec2-internetgateway: aws_internet_gateway
  aws-ec2-networkaclentry: aws_network_acl
  aws-ec2-routeserverpeer: aws_vpc_route_server_peer
  aws-ec2-subnetcidrblock: aws_vpc_ipv4_cidr_block_association
  aws-ec2-networkinterface: aws_network_interface
  aws-ec2-volumeattachment: aws_volume_attachment
  aws-ec2-clientvpnendpoint: aws_ec2_client_vpn_endpoint
  aws-ec2-localgatewayroute: aws_ec2_local_gateway_route
  aws-ec2-vpcendpointservice: aws_vpc_endpoint_service
  aws-ec2-vpnconnectionroute: aws_vpn_connection_route
  aws-ec2-capacityreservation: aws_ec2_capacity_reservation
  aws-ec2-networkinsightspath: aws_ec2_network_insights_path
  aws-ec2-routeserverendpoint: aws_vpc_route_server_endpoint
  aws-ec2-securitygroupegress: aws_security_group_rule
  aws-ec2-trafficmirrorfilter: aws_ec2_traffic_mirror_filter
  aws-ec2-trafficmirrortarget: aws_ec2_traffic_mirror_target
  aws-ec2-transitgatewayroute: aws_ec2_transit_gateway_route
  aws-ec2-verifiedaccessgroup: aws_verifiedaccess_group
  aws-ec2-trafficmirrorsession: aws_ec2_traffic_mirror_session
  aws-ec2-vpcgatewayattachment: aws_internet_gateway_attachment
  aws-ec2-vpcpeeringconnection: aws_vpc_peering_connection
  aws-ec2-ipamresourcediscovery: aws_vpc_ipam_resource_discovery
  aws-ec2-transitgatewayconnect: aws_ec2_transit_gateway_connect
  aws-ec2-localgatewayroutetable: aws_ec2_local_gateway_route_table
  aws-ec2-routeserverassociation: aws_vpc_route_server_vpc_association
  aws-ec2-routeserverpropagation: aws_vpc_route_server_propagation
  aws-ec2-verifiedaccessendpoint: aws_verifiedaccess_endpoint
  aws-ec2-verifiedaccessinstance: aws_verifiedaccess_instance
  aws-ec2-instanceconnectendpoint: aws_ec2_instance_connect_endpoint
  aws-ec2-networkinsightsanalysis: aws_ec2_network_insights_analysis
  aws-ec2-trafficmirrorfilterrule: aws_ec2_traffic_mirror_filter_rule
  aws-ec2-capacityreservationfleet: aws_ec2_capacity_reservation
  aws-ec2-transitgatewayattachment: aws_ec2_transit_gateway_attachment
  aws-ec2-transitgatewayroutetable: aws_ec2_transit_gateway_route_table
  aws-ec2-egressonlyinternetgateway: aws_egress_only_internet_gateway
  aws-ec2-snapshotblockpublicaccess: aws_ebs_snapshot_block_public_access
  aws-ec2-transitgatewayconnectpeer: aws_ec2_transit_gateway_connect_peer
  aws-ec2-vpcdhcpoptionsassociation: aws_vpc_dhcp_options_association
  aws-ec2-clientvpnauthorizationrule: aws_ec2_client_vpn_authorization_rule
  aws-ec2-networkinsightsaccessscope: aws_ec2_network_insights_path
  aws-ec2-networkinterfaceattachment: aws_network_interface_attachment
  aws-ec2-networkinterfacepermission: aws_network_interface_permission
  aws-ec2-vpngatewayroutepropagation: aws_vpn_gateway_route_propagation
  aws-ec2-ippoolroutetableassociation: aws_vpc_endpoint_route_table_association
  aws-ec2-securitygroupvpcassociation: aws_vpc_security_group_vpc_association
  aws-ec2-subnetnetworkaclassociation: aws_network_acl_association
  aws-ec2-subnetroutetableassociation: aws_route_table_association
  aws-ec2-transitgatewayvpcattachment: aws_ec2_transit_gateway_vpc_attachment
  aws-ec2-verifiedaccesstrustprovider: aws_verifiedaccess_trust_provider
  aws-ec2-vpcblockpublicaccessoptions: aws_vpc_block_public_access_options
  aws-ec2-gatewayroutetableassociation: aws_ec2_transit_gateway_route_table_associations
  aws-ec2-localgatewayvirtualinterface: aws_ec2_local_gateway_virtual_interface
  aws-ec2-transitgatewaymulticastdomain: aws_ec2_transit_gateway_multicast_domain
  aws-ec2-vpcblockpublicaccessexclusion: aws_vpc_block_public_access_exclusion
  aws-ec2-vpcendpointservicepermissions: aws_vpc_endpoint_service_allowed_principal
  aws-ec2-transitgatewaypeeringattachment: aws_ec2_transit_gateway_peering_attachment
  aws-ec2-ipamresourcediscoveryassociation: aws_vpc_ipam_resource_discovery_association
  aws-ec2-clientvpntargetnetworkassociation: aws_ec2_client_vpn_network_association
  aws-ec2-localgatewayvirtualinterfacegroup: aws_ec2_local_gateway_virtual_interface_group
  aws-ec2-vpcendpointconnectionnotification: aws_vpc_endpoint_connection_notification
  aws-ec2-transitgatewaymulticastgroupmember: aws_ec2_transit_gateway_multicast_group_member
  aws-ec2-transitgatewaymulticastgroupsource: aws_ec2_transit_gateway_multicast_group_source
  aws-ec2-transitgatewayroutetableassociation: aws_ec2_transit_gateway_route_table_association
  aws-ec2-transitgatewayroutetablepropagation: aws_ec2_transit_gateway_route_table_propagation
  aws-ec2-networkperformancemetricsubscription: aws_vpc_network_performance_metric_subscription
  aws-ec2-transitgatewaymulticastdomainassociation: aws_ec2_transit_gateway_multicast_domain_association
Excluded:
  - aws-ec2-securitygroupingress
  - aws-ec2-networkinsightsaccessscopeanalysis
  - aws-ec2-enclavecertificateiamroleassociation
  - aws-ec2-localgatewayroutetablevirtualinterfacegroupassociation
