ApiSchemas:
  availabilitySets: "2024-11-01"
  capacityReservationGroups: "2024-11-01"
  capacityReservationGroups_capacityReservations: "2024-11-01"
  cloudServices: "2024-11-04"
  diskAccesses: "2025-01-02"
  diskAccesses_privateEndpointConnections: "2025-01-02"
  diskEncryptionSets: "2025-01-02"
  disks: "2025-01-02"
  galleries: "2024-03-03"
  galleries_applications: "2024-03-03"
  galleries_applications_versions: "2024-03-03"
  galleries_images: "2024-03-03"
  galleries_images_versions: "2024-03-03"
  galleries_inVMAccessControlProfiles: "2024-03-03"
  galleries_inVMAccessControlProfiles_versions: "2024-03-03"
  hostGroups: "2024-11-01"
  hostGroups_hosts: "2024-11-01"
  images: "2024-11-01"
  proximityPlacementGroups: "2024-11-01"
  restorePointCollections: "2024-11-01"
  restorePointCollections_restorePoints: "2024-11-01"
  snapshots: "2025-01-02"
  sshPublicKeys: "2024-11-01"
  virtualMachineScaleSets: "2024-11-01"
  virtualMachineScaleSets_virtualMachines_extensions: "2024-11-01"
  virtualMachineScaleSets_virtualMachines_runCommands: "2024-11-01"
  virtualMachineScaleSets_virtualMachines: "2024-11-01"
  virtualMachines: "2024-11-01"

Resources:
  availabilitySets: azurerm_availability_set
  capacityReservationGroups: azurerm_capacity_reservation_group
  capacityReservationGroups_capacityReservations: azurerm_capacity_reservation
  diskAccesses: azurerm_disk_access
  diskEncryptionSets: azurerm_disk_encryption_set
  disks: azurerm_managed_disk
  galleries_applications: azurerm_gallery_application
  galleries_applications_versions: azurerm_gallery_application_version
  galleries_images: azurerm_shared_image_gallery
  hostGroups: azurerm_dedicated_host_group
  hostGroups_hosts: azurerm_dedicated_host
  images: azurerm_image
  proximityPlacementGroups: azurerm_proximity_placement_group
  restorePointCollections: azurerm_restore_point_collection
  restorePointCollections_restorePoints: azurerm_virtual_machine_restore_point
  snapshots: azurerm_snapshot
  sshPublicKeys: azurerm_ssh_public_key
  virtualMachineScaleSets: azurerm_virtual_machine_scale_set
  virtualMachineScaleSets_virtualMachines_extensions: azurerm_virtual_machine_scale_set_extension
  virtualMachines: azurerm_virtual_machine
Excluded:
  - cloudServices
  - diskAccesses_privateEndpointConnections
  - galleries
  - galleries_inVMAccessControlProfiles
  - galleries_inVMAccessControlProfiles_versions
  - virtualMachineScaleSets_virtualMachines_runCommands
  - virtualMachineScaleSets_virtualMachines
  - virtualMachines_extensions
  - virtualMachines_runCommands
